force-app/main/default/objects/Dynamic_Content__c/Dynamic_Content__c.object-meta.xml
<CustomObject>
    <description>Different kinds of content used in the Dynamic Banner component.</description>
    <label>Dynamic Content</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Dynamic Content</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Content__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should this content be actively used in the Dynamic Banner component?</description>
    <inlineHelpText>Should this content be actively used in the Dynamic Banner component?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <description>What type of content does this record represent?  Different types of content are used in different ways.</description>
    <inlineHelpText>What type of content does this record represent?  Different types of content are used in different ways.</inlineHelpText>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Button - Flow</fullName>
            </value>
            <value>
                <fullName>Button - Link</fullName>
            </value>
            <value>
                <fullName>Content Card</fullName>
            </value>
            <value>
                <fullName>Metric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/Flow_URL__c.field-meta.xml
<CustomField>
    <fullName>Flow_URL__c</fullName>
    <description>Flow API name or hyperlink/URL to direct the user to when they click on this content</description>
    <inlineHelpText>Flow API name or hyperlink/URL to direct the user to when they click on this content</inlineHelpText>
    <label>Flow/URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>SLDS icon to display</description>
    <inlineHelpText>SLDS icon to display</inlineHelpText>
    <label>Icon</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <description>Unique reference used to decide where this record&apos;s content should be used</description>
    <inlineHelpText>Unique reference used to decide where this record&apos;s content should be used</inlineHelpText>
    <label>Tag</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/Title_Label__c.field-meta.xml
<CustomField>
    <fullName>Title_Label__c</fullName>
    <description>Title/headline/label</description>
    <inlineHelpText>Title/headline/label</inlineHelpText>
    <label>Title/Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dynamic_Content__c/fields/URL_Behavior__c.field-meta.xml
<CustomField>
    <fullName>URL_Behavior__c</fullName>
    <description>When clicked, should the URL be visited in the same window/tab (_self) or a new one (_new)?</description>
    <inlineHelpText>When clicked, should the URL be visited in the same window/tab (_self) or a new one (_new)?</inlineHelpText>
    <label>URL Behavior</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>_self</fullName>
            </value>
            <value>
                <fullName>_new</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicBannerController.cls
public class DynamicBannerController {
    // Queries for the info of the current user
    @AuraEnabled(cacheable=true)
    public static List<User> getUser(String userId) {
        return [SELECT Id,
                FirstName,
                LastName,
                FullPhotoUrl
                FROM User
                WHERE Id = :userId
                LIMIT 1];
    }
    
    // Returns all active Dynamic_Content__c records
    // for a given Content_Type__c and Tag__c
    @AuraEnabled
    public static List<Dynamic_Content__c> getDynamicContentRecords(String ParamTag, String ParamContentType){
        if(String.isBlank(ParamTag)){
            // return all active records, no matter what the Tag is
            return [SELECT Content_Type__c,Flow_URL__c,Description__c,Icon__c,Title_Label__c,URL_Behavior__c FROM Dynamic_Content__c WHERE Content_Type__c LIKE :(ParamContentType + '%') AND Active__c = TRUE AND Tag__c = 'all' ORDER BY Display_Order__c ASC];
        }
        else {
            // return only the active records associated with the Tag
            return [SELECT Content_Type__c,Flow_URL__c,Description__c,Icon__c,Title_Label__c,URL_Behavior__c FROM Dynamic_Content__c WHERE Content_Type__c LIKE :(ParamContentType + '%') AND Active__c = TRUE AND (Tag__c =: ParamTag OR Tag__c = 'all') ORDER BY Display_Order__c ASC];
        }
    }
}