force-app/main/default/objects/Account/fields/Farm_Plot_Number__c.field-meta.xml
<CustomField>
    <fullName>Farm_Plot_Number__c</fullName>
    <label>Farm/Plot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Sale__c</fullName>
    <label>Year of Sale</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Food_Production__c/Food_Production__c.object-meta.xml
<CustomObject>
    <description>Individual submission by species, stating quantity and price</description>
    <label>Food Production</label>
    <nameField>
        <displayFormat>FP-{000000}</displayFormat>
        <label>Food Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Production</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Production__c/fields/Average_Price__c.field-meta.xml
<CustomField>
    <fullName>Average_Price__c</fullName>
    <label>Average Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Food_Production__c/fields/Fingerlings_Eggs_Species__c.field-meta.xml
<CustomField>
    <fullName>Fingerlings_Eggs_Species__c</fullName>
    <label>Fingerlings / Eggs Species</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Food_Production__c/fields/Food_Production_Submission__c.field-meta.xml
<CustomField>
    <fullName>Food_Production_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Food Production Submission</label>
    <referenceTo>Food_Production_Submission__c</referenceTo>
    <relationshipLabel>Food Production</relationshipLabel>
    <relationshipName>Food_Production</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Food_Production__c/fields/Species_of_Fish__c.field-meta.xml
<CustomField>
    <fullName>Species_of_Fish__c</fullName>
    <label>Species of Fish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asian Seabass 金目鲈</fullName>
            </value>
            <value>
                <fullName>Black-Spotted Grouper 黑点斑</fullName>
            </value>
            <value>
                <fullName>Flower Crab 花蟹</fullName>
            </value>
            <value>
                <fullName>Giant Grouper 龙胆</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Production__c/fields/Transhipped__c.field-meta.xml
<CustomField>
    <fullName>Transhipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transhipped?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Food_Production__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pc</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/Food_Production_Submission__c.object-meta.xml
<CustomObject>
    <label>Food Production Submission</label>
    <nameField>
        <displayFormat>FPS-{000000}</displayFormat>
        <label>Food Production Submission</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Production Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Production_Submission__c/fields/Average_Price__c.field-meta.xml
<CustomField>
    <fullName>Average_Price__c</fullName>
    <label>Average Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/fields/Farm_Plot_Number__c.field-meta.xml
<CustomField>
    <fullName>Farm_Plot_Number__c</fullName>
    <label>Farm/Plot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/fields/Sale_Period__c.field-meta.xml
<CustomField>
    <fullName>Sale_Period__c</fullName>
    <label>Sale Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>q1</fullName>
                <label>Jan-Mar 一月至三月</label>
            </value>
            <value>
                <fullName>q2</fullName>
                <label>Apr-Jun 四月至六月</label>
            </value>
            <value>
                <fullName>q3</fullName>
                <label>July-Sep 七月至九月</label>
            </value>
            <value>
                <fullName>q4</fullName>
                <label>Oct-Dec 十月至十二月</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/fields/Species_of_Fish__c.field-meta.xml
<CustomField>
    <fullName>Species_of_Fish__c</fullName>
    <label>Species of Fish</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asian Seabass 金目鲈</fullName>
            </value>
            <value>
                <fullName>Black-Spotted Grouper 黑点斑</fullName>
            </value>
            <value>
                <fullName>Flower Crab 花蟹</fullName>
            </value>
            <value>
                <fullName>Giant Grouper 龙胆</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Adjustment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Production_Submission__c/fields/Year_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Sale__c</fullName>
    <inlineHelpText>Year of Sale in YYYY/DD</inlineHelpText>
    <label>Year of Sale (销售年份)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Food_Supply_Tracing__c/Food_Supply_Tracing__c.object-meta.xml
<CustomObject>
    <label>Food Supply Tracing</label>
    <nameField>
        <label>Food  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Supply Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Supply_Tracing__c/fields/Affected_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Affected_Lot_Number__c</fullName>
    <label>Affected Lot Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Food_Supply_Tracing__c/fields/Reason_for_Tracing__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Tracing__c</fullName>
    <label>Reason for Tracing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food Contamination</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food_Supply_Tracing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending Authority Decision</fullName>
            </value>
            <value>
                <fullName>Food Recall Triggered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/Supply_Chain__c.object-meta.xml
<CustomObject>
    <label>Supply Chain</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Food  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Chain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supply_Chain__c/fields/Days_Since_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Initiated__c</fullName>
    <formula>NOW() -Initiated_Declaration_Request_On__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Initiated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Food_Supply_Tracing__c.field-meta.xml
<CustomField>
    <fullName>Food_Supply_Tracing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Food Supply Tracing</label>
    <referenceTo>Food_Supply_Tracing__c</referenceTo>
    <relationshipLabel>Supply Chain</relationshipLabel>
    <relationshipName>Supply_Chain</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Is_End_Node__c.field-meta.xml
<CustomField>
    <fullName>Is_End_Node__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is End Node</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Reported_By__c.field-meta.xml
<CustomField>
    <fullName>Reported_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicate the company who reported this record</description>
    <label>Reported By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chain (Originally Reported By)</relationshipLabel>
    <relationshipName>Supply_Chain2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Source_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Source_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Source Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Source_From__c.field-meta.xml
<CustomField>
    <fullName>Source_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source From</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chain</relationshipLabel>
    <relationshipName>Supply_Chain</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Source_From_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_From_Name__c</fullName>
    <formula>Source_From__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source From Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Initiated Entry</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Require Follow Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Supply_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Supply_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supply Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Supply_To__c.field-meta.xml
<CustomField>
    <fullName>Supply_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supply To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chain (Supply To)</relationshipLabel>
    <relationshipName>Supply_Chain1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Supply_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Supply_To_Name__c</fullName>
    <formula>Supply_To__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supply To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Timeliness__c.field-meta.xml
<CustomField>
    <fullName>Timeliness__c</fullName>
    <formula>IF( Days_Since_Initiated__c &lt; 3, &apos;🟢&apos;,IF(Days_Since_Initiated__c &lt;6, &apos;🟡&apos;, &apos;🔴&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timeliness</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supply_Chain__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Piece</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>L (litre)</fullName>
            </value>
            <value>
                <fullName>m (metre)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductionDataController.cls
public class ProductionDataController {
    public ProductionDataController() {

    }

    @AuraEnabled
    public static List<Food_Production__c> getFisheryData(String farmId, String year, String period){
        //Query data based on last year's data. AS of now,we may hardcode the farmID to retrieve specific set of records

        System.debug('farmId:'+farmId);
        System.debug('year:' + year);
        System.debug('period:'+period);
        //first attempt to see if there is draft data. 
        List<Food_Production__c> foodProductionList = [Select Id,Species_of_Fish__c,Fingerlings_Eggs_Species__c, Quantity__c,Transhipped__c,Unit_of_Measure__c,Average_Price__c,Food_Production_Submission__c,Food_Production_Submission__r.Year_of_Sale__c,Food_Production_Submission__r.Sale_Period__c FROM Food_Production__c WHERE Food_Production_Submission__r.Farm_Plot_Number__c =:farmId AND  Food_Production_Submission__r.Year_of_Sale__c =: year AND Food_Production_Submission__r.Sale_Period__c =: period AND  Food_Production_Submission__r.Status__c = 'Draft'];

        system.debug('Period is '+ period);
        //No Draft Data
       /* if(foodProductionList.isEmpty()){
            //Get previous year data. 
            Integer lastYear = Integer.valueOf(year); 
            lastYear = lastYear - 1; 
            year = String.valueOf(lastYear); 
            system.debug('Last year is '+ year );
            foodProductionList = [Select Species_of_Fish__c,Fingerlings_Eggs_Species__c, Quantity__c,Transhipped__c,Unit_of_Measure__c,Average_Price__c,Food_Production_Submission__c,Food_Production_Submission__r.Year_of_Sale__c,Food_Production_Submission__r.Sale_Period__c FROM Food_Production__c WHERE Food_Production_Submission__r.Farm_Plot_Number__c =:farmId AND  Food_Production_Submission__r.Year_of_Sale__c =: year AND Food_Production_Submission__r.Sale_Period__c =: period];
        }*/

        //Check if there is existing data in draft status for current period, if there are retrieve that to use these data
        //If there are no pending submission, then proceed to retrieve the data from the the same period last year 
        return foodProductionList; 
        
    }

    @AuraEnabled
    public static List<Food_Production__c> getPastFisheryData(String farmId, String year, String period){
        //Query data based on last year's data. AS of now,we may hardcode the farmID to retrieve specific set of records

        System.debug('farmId:'+farmId);
        System.debug('year:' + year);
        System.debug('period:'+period);

        //Get previous year data. 
        Integer lastYear = Integer.valueOf(year); 
        lastYear = lastYear - 1; 
        year = String.valueOf(lastYear); 
        system.debug('Last year is '+ year );
        List<Food_Production__c> foodProductionList = [Select Id,Species_of_Fish__c,Fingerlings_Eggs_Species__c, Quantity__c,Transhipped__c,Unit_of_Measure__c,Average_Price__c,Food_Production_Submission__c,Food_Production_Submission__r.Year_of_Sale__c,Food_Production_Submission__r.Sale_Period__c FROM Food_Production__c WHERE Food_Production_Submission__r.Farm_Plot_Number__c =:farmId AND  Food_Production_Submission__r.Year_of_Sale__c =: year AND Food_Production_Submission__r.Sale_Period__c =: period];
    
        //Check if there is existing data in draft status for current period, if there are retrieve that to use these data
        //If there are no pending submission, then proceed to retrieve the data from the the same period last year 
        return foodProductionList; 
        
    }

    @InvocableMethod(label='Get Default Quarter Year' description='To help with defaulting the quarter and year input')
    public static List<String> getDefaultYearPeriod(List<String> yearQtr){
        Date todayDate = date.today();
        Integer currentYearInt = todayDate.year();
        Integer currentMonthInt =  todayDate.month();
        Integer quarter; 
        String quarterStr = '';
        String yearStr = '';

        //adjust year and quarter if user input data on the last month of the year
        if(currentMonthInt == 12){
            currentYearInt = currentYearInt + 1;
            currentMonthInt = 1; 
            quarterStr = 'q1';
        }

        yearStr = String.valueOf(currentYearInt);

        quarter = (currentMonthInt+1)/3;
        if(quarter == 0)
            quarterStr = 'q1';
        else if(quarter == 1)
            quarterStr = 'q2';
        else if (quarter == 2)
            quarterStr = 'q3';
        else 
            quarterStr = 'q4';

        System.debug('current year is '+ yearStr);

        List<List<String>> nestedList = new List<List<String>>();
        List<String> returnData = new List<String>();
        //returnData.add(quarterStr); 
        //returnData.add(yearStr);
        nestedList.add(returnData);
        if(yearQtr[0] == 'year'){
            returnData.add(yearStr);
        }else{
            returnData.add(quarterStr); 
        }
        return returnData;
    }

    @AuraEnabled
    public static Boolean removeFoodProductRecord(Id productionId){
        Food_Production__c foodProductRecord = new Food_Production__c(Id = productionId);
        try{
            delete foodProductRecord; 
            return true; 
        }catch(Exception e){
            system.debug('Exception captured: ' + e.getMessage());
            return false;
        }
    }

    @AuraEnabled
    public static Boolean insertUpdateNewProductionRecords(String parendtId, List<Food_Production__c> insertProductionList, List<Food_Production__c> updateProductionList){
        try{
            system.debug('update data list'+updateProductionList);
           insert insertProductionList;
           update updateProductionList;
            return true; 
        }catch(Exception e){
            system.debug('Exception captured: ' + e.getMessage());
            return false;
        }
    }

    @AuraEnabled
    public static List<Supply_Chain__c> getSupplyChainData(String foodTracingId){
        //Query data based on last year's data. AS of now,we may hardcode the farmID to retrieve specific set of records

        //Get previous year data. 
        List<Supply_Chain__c> supplyChainData = [Select Id,Days_Since_Initiated__c,Reported_By__c, Reported_By__r.Name,Source_From__c, Source_From_Name__c,Supply_To__c, Supply_To_Name__c,Status__c, Quantity__c,Unit_of_Measure__c,Source_Confirmed__c,Supply_Confirmed__c,Is_End_Node__c, Timeliness__c, Food_Supply_Tracing__c FROM Supply_Chain__c WHERE Food_Supply_Tracing__c=: foodTracingId];
    
        //Check if there is existing data in draft status for current period, if there are retrieve that to use these data
        //If there are no pending submission, then proceed to retrieve the data from the the same period last year 
        return supplyChainData; 
        
    }

    //Product__c
    @AuraEnabled
    public static List<Food_Supply_Tracing__c> getFoodSupplyTracingData(String foodTracingId){
        //Query data based on last year's data. AS of now,we may hardcode the farmID to retrieve specific set of records

        //Get previous year data. 
        List<Food_Supply_Tracing__c> supplyChainData = [Select Id, Product__c,Affected_Lot_Number__c, Reason_for_Tracing__c,Status__c,Target_Completion_Date__c FROM Food_Supply_Tracing__c WHERE Id=: foodTracingId];
    
        //Check if there is existing data in draft status for current period, if there are retrieve that to use these data
        //If there are no pending submission, then proceed to retrieve the data from the the same period last year 
        return supplyChainData; 
        
    }

    @AuraEnabled
    public static List<Account> getAccountData(List<String> accountList){
        //Query data based on last year's data. AS of now,we may hardcode the farmID to retrieve specific set of records
        //String dynamicString = String.join(',', accountList.stream().map(p -> '\'' + p + '\'').collect(Collectors.toList()));

        //Get previous year data. 
        List<Account> accountRecords = [Select id, type, Name FROM Account WHERE Id IN: accountList];
    
        //Check if there is existing data in draft status for current period, if there are retrieve that to use these data
        //If there are no pending submission, then proceed to retrieve the data from the the same period last year 
        return accountRecords; 
        
    }

    
}