force-app/main/default/objects/BusinessLicenseApplication/fields/Coordinates__c.field-meta.xml
<CustomField>
    <fullName>Coordinates__c</fullName>
    <label>Coordinates</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BusinessLicenseApplication/fields/Type_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Work__c</fullName>
    <label>Type of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Expansion</fullName>
            </value>
            <value>
                <fullName>Building Demolition</fullName>
            </value>
            <value>
                <fullName>Removal of a Tree</fullName>
            </value>
            <value>
                <fullName>Removal of a Tree Stump</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicenseApplication/fields/Work_Entity_Information__c.field-meta.xml
<CustomField>
    <fullName>Work_Entity_Information__c</fullName>
    <label>Work Entity Information</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Property Owner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESRIDisplayMapController.cls
public class ESRIDisplayMapController {
   
    public String CenterAddress {
        get {
            
            for(BusinessLicenseApplication c: landInfo) {
                CenterAddress = c.Account.BillingStreet + ',' + c.Account.BillingCity + ',' + c.Account.BillingState + ',' + c.Account.BillingPostalCode;
            }
            return CenterAddress;            
        } 
        set;
    }
    
    public String PolygonCoordinates {
        get {
            
            for(BusinessLicenseApplication c: landInfo) {
                PolygonCoordinates = c.Coordinates__c;
            }
            return PolygonCoordinates;            
        } 
        set;
    }
    
    public String TypeOfWork {
        get {
            
            for(BusinessLicenseApplication c: landInfo) {
                TypeOfWork = c.Type_of_Work__c;
            }
            return TypeOfWork;            
        } 
        set;
    }
    
    public String WorkEntity {
        get {
            
            for(BusinessLicenseApplication c: landInfo) {
                WorkEntity = c.Work_Entity_Information__c;
            }
            return WorkEntity;            
        } 
        set;
    }
    
    public String AccountName {
        get {
            
            for(BusinessLicenseApplication c: landInfo) {
                AccountName = c.Account.Name;
            }
            return AccountName;            
        } 
        set;
    }

    public List<BusinessLicenseApplication> landInfo {get; set;}
    
    public ESRIDisplayMapController() {
        // Get the BLA and Coordinates information
        landInfo = [SELECT Coordinates__c, Account.Name, Account.BillingStreet,Account.BillingState,Account.BillingCity,Account.BillingPostalCode,Type_of_Work__c, Work_Entity_Information__c FROM BusinessLicenseApplication  WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        System.debug('ESRIDisplayMapController: landInfo: [' + landInfo + ']');
    }
}